/**
 * 13以前における_app.tsxみたいな役割を担う
 */
import "./globals.css";
import Link from "next/link";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // fetch("/hoge", { cache: "no-store" })
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <ul style={{ display: "flex", gap: "16px", listStyle: "none", background: "cyan", color: "black" }}>
          <li><Link href={"/"}>Top</Link></li>
          <li><Link href={"/dashboard"}>Dashboard</Link></li>
        </ul>
        {children}
      </body>
    </html>
  );
}
